rm /usr/local/bin/bounce.exe
rm /usr/local/bin/kraken.exe
rm /usr/local/bin/krakenc.exe
#rm /usr/local/bin/bellhop3d.exe
#rm /usr/local/bin/bellhop.exe
rm /usr/local/bin/field.exe
rm /usr/local/bin/field3d.exe
#rm /usr/local/bin/scooter.exe
#rm /usr/local/bin/sparc.exe
rm /usr/local/bin/bellhop.exe
rm /usr/local/bin/bellhop3d.exe
rm /usr/local/bin/scooter.exe
rm /usr/local/bin/sparc.exe
